blank_issues_enabled: false
contact_links:
  - name: Telegram 频道
    url: https://t.me/biliroaming
    about: 可以订阅更新、讨论交流
  - name: QQ 频道
    url: https://qun.qq.com/qqweb/qunpro/share?_wv=3&_wwv=128&inviteCode=NVoD5&from=246610&biz=ka
    about: 可以订阅更新、讨论交流