name: 添加公共服务器
description: 把自己的服务器添加到公共服务器列表
labels: [server]
title: "[Server] "
body:
  - type: input
    id: contact
    attributes:
      label: 联系方式
      description: Telegram、Github 账号等联系方式
    validations:
      required: true
  - type: input
    id: domain
    attributes:
      label: 域名
      description: 服务器域名
    validations:
      required: true
  - type: checkboxes
    id: areas
    attributes:
      label: 支持地区
      description: 服务器支持解析的地区
      options:
        - label: 中国大陆
        - label: 港澳
        - label: 台湾
        - label: 东南亚
  - type: checkboxes
    id: premium
    attributes:
      label: 带会员专享
      options:
        - label: 服务器只有带会员用户能解析
  - type: input
    id: sponsor
    attributes:
      label: 赞助地址
      description: 爱发电等
